name: Install Conda (+ RocheCert + Arvados-CLI)
on: 
  push:
    paths:
    - 'Dockerfile.RocheCertConda2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and publish on Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matmu/arvados-cli
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        dockerfile: Dockerfile.RocheCertConda2
        tags: "RocheCertConda2"
